---
- name: rsyslog tasks
  import_tasks:
    - rsyslog.yml

- name: sysctl tasks
  import_tasks:
    - sysctl.yml

- name: add banner
  import_tasks:
     - banner.yml

- name: Give insecure permissions to an existing file
  import_tasks:
     - permission.yml

- name: add module to kernel
  import_tasks: 
      - grub.yml
