---
- name: Change file ownership, group and permissions
  ansible.builtin.file:
      path: "{{ item.path }}"
      mode: "{{ item.mode }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
  loop: 
    
    - { path: "/etc/cron.d", mode: go-rwx,  owner: root , group: root }
    - { path: "/etc/cron.daily", mode: go-rwx, owner: root , group: root}
    
    - { path: "/etc/cron.hourly", mode: go-rwx, owner: root , group: root }
    - { path: "/etc/cron.monthly", mode: go-rwx , owner: root , group: root }
    - { path: "/etc/cron.weekly", mode: go-rwx, owner: root , group: root }
    
    - { path: "/etc/crontab", mode: go-rwx , owner: root , group: root  }
    # - { path: "/etc/cron.allow", mode: go-rwx, owner: root , group: root }
   # - { path: "/etc/at.allow", mode: go-rwx, owner: root , group: root  }
    - { path: "/etc/ssh/sshd_config", mode: go-rwx , owner: root , group: root}
    - { path: "/etc/passwd", mode: 644, owner: root , group: root}
    - { path: "/etc/shadow", mode: 644 , owner: root , group: root}
    - { path: "/etc/group", mode: u-x,g-wx,o-wx, owner: root, group: root }
    
- name: Change mode file ownership, group and permissions
  ansible.builtin.file:
      path: "{{ item.path }}"
      mode: "{{ item.mode }}"
  
  loop:
    -  { path: "/boot/grub/grub.cfg", mode:  o-wx }
    - { path: "/etc/issue", mode: go-rwx } 
    - { path: "/etc/issue.net", mode: go-rwx }
  #  - { path: "/etc/motd", mode: go-rwx }
   # - { path: "/etc/cron.deny", mode: go-rwx }
   # - { path: "/etc/ssh_private_host_key", mode: go-rwx }